### PR TITLE
TextureFX core

### PR DESCRIPTION
**Pull request by bj-rn**
Adds TextureFX currently marked as core here:
https://cryptpad.fr/sheet/#/2/sheet/edit/wu-HEppevxpFch7s6SLRgzv+/

- ChangeFormat
- Swizzle
- ToLinear

### CODE REVIEW

**Comment by tebjan** [comment]
Great, just add I set the list, do we have ToGamma already?

**Comment by bj-rn** [comment]
There was none - I added a node now. Don't know if it makes sense to add the method to https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Graphics/Shaders/ColorUtility.sdsl or https://github.com/vvvv/VL.Stride/blob/develop/packages/VL.Stride.Runtime/src/Effects/Common/ShaderUtils.sdsl.

**Comment by tebjan** [comment]
Yes, it would be nice to PR that to the Stride ColorUtility.

The color conversion topic is quite fundamental, and a simple pow(2.2) is incorrect when we talk about RGB/sRGB conversions. and it is the other direction. here is an article about fast approximations for shaders:

http://chilliant.blogspot.com/2012/08/srgb-approximations-for-hlsl.html

and we should probably also have the mathematically "correct" version of it. either as a technique or a second version.
I found a code snippet for GLSL which implements the formulas as defined by the sRGB standard without branching:

```c
// Converts a color from linear light gamma to sRGB gamma
vec4 fromLinear(vec4 linearRGB)
{
    bvec4 cutoff = lessThan(linearRGB, vec4(0.0031308));
    vec4 higher = vec4(1.055)*pow(linearRGB, vec4(1.0/2.4)) - vec4(0.055);
    vec4 lower = linearRGB * vec4(12.92);

    return mix(higher, lower, cutoff);
}

// Converts a color from sRGB gamma to linear light gamma
vec4 toLinear(vec4 sRGB)
{
    bvec4 cutoff = lessThan(sRGB, vec4(0.04045));
    vec4 higher = pow((sRGB + vec4(0.055))/vec4(1.055), vec4(2.4));
    vec4 lower = sRGB/vec4(12.92);

    return mix(higher, lower, cutoff);
}
```

also naming-wise, we could think about names that include sRGB instead of gamma, which is really what this is all about. @azeno  what do you think?

**Comment by bj-rn** [comment]
There seem to be some instances in Stride were the "incorrect" conversion is also used. Maybe they should be corrected too. A quick search turned up with these, there might be more. 
[SignedDistanceFieldFontImporter.cs](https://github.com/stride3d/stride/blob/6a0532966b8c907c5a6c46033788fd14548842fc/sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs#L230)
[SpriteEffectExtTexture.sdsl](https://github.com/stride3d/stride/blob/6a0532966b8c907c5a6c46033788fd14548842fc/sources/engine/Stride.Graphics/Shaders/SpriteEffectExtTexture.sdsl#L85)
[ToneMapHejlDawsonOperatorShader.sdsl](https://github.com/stride3d/stride/blob/6a0532966b8c907c5a6c46033788fd14548842fc/sources/engine/Stride.Rendering/Rendering/Images/ColorTransforms/ToneMap/ToneMapHejlDawsonOperatorShader.sdsl#L20)
[TrueTypeImporter.cs](https://github.com/stride3d/stride/blob/6a0532966b8c907c5a6c46033788fd14548842fc/sources/engine/Stride.Assets/SpriteFont/Compiler/TrueTypeImporter.cs#L212)

**Comment by tebjan** [comment]
yes and no, some of these are correct. gamma and sRGB are two different things, although their curves are very similar. sRGB is an encoding/compression to store colors in better precision in 8 bits per channel data.

gamma space is a color space that converts from linear space to the gamma curve of the monitor that is used to display the color.

> Colors represented in linear color space can be mutually added and multiplied. Colors represented in a gamma color space cannot be mutually added, but can be mutually multiplied. Colors represented in sRGB color space can neither be mutually added nor multiplied.

here is a bit more info on that:
https://matt77hias.github.io/blog/2018/07/01/linear-gamma-and-sRGB-color-spaces.html

so the nodes should definitely state whether their intended use is to encode/decode sRGB or whether they convert between gamma and linear space.

**Comment by bj-rn** [comment]
Consider me confused. Trying make sense of things.

**ToLinear**
might better be called _sRGBTolinearRGB_
uses ToLinear from [ColorUtility.](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Graphics/Shaders/ColorUtility.sdsl) which in turn uses approximations posted [here](http://chilliant.blogspot.com/2012/08/srgb-approximations-for-hlsl.html).

**ToGamma**
The node you were actually asking for in your first post is rather _Light?Gamma(RGB)TosRGB_ which is is converting a ?gamma corrected linear RGB? to sRGB and should use:

```
// Converts a color from linear light gamma to sRGB gamma
vec4 fromLinear(vec4 linearRGB)
{
    bvec4 cutoff = lessThan(linearRGB, vec4(0.0031308));
    vec4 higher = vec4(1.055)*pow(linearRGB, vec4(1.0/2.4)) - vec4(0.055);
    vec4 lower = linearRGB * vec4(12.92);

    return mix(higher, lower, cutoff);
}
```
Then there would be another node called _sRGBToLight?Gamma(RGB)_ using:
```
// Converts a color from sRGB gamma to linear light gamma
vec4 toLinear(vec4 sRGB)
{
    bvec4 cutoff = lessThan(sRGB, vec4(0.04045));
    vec4 higher = pow((sRGB + vec4(0.055))/vec4(1.055), vec4(2.4));
    vec4 lower = sRGB/vec4(12.92);

    return mix(higher, lower, cutoff);
}
```
To have the inverse of the initial _ToLinear_  there would be yet another node _linearRGBTosRGB_ which according to the blogpost above would do something like:
```
float3 S1 = sqrt(RGB);
float3 S2 = sqrt(S1);
float3 S3 = sqrt(S2);
float3 sRGB = 0.662002687 * S1 + 0.684122060 * S2 - 0.323583601 * S3 - 0.0225411470 * RGB;
```
The naive _ToGamma_ node I made could maybe be renamed to _GammaCorrect (Simple)_ or _CorrectGamma(Simple)_

**Comment by mhusinsky** [comment]
thank you for your work on this topic - i find this highly important to get this right. 

in this regard we probably also should consider other transfer functions, especially from television formats (e.g. ITU-Rec709), which are again different from sRGB.  [see here for an example](https://www.image-engineering.de/products/charts/sort-by-type/126-library/technote/714-color-spaces-rec-709-vs-srgb), or [Poyntons Gamma FAQ, point 6](https://poynton.ca/PDFs/GammaFAQ.pdf).

**Comment by bj-rn** [comment]
Posted this already in the first pull request but anyway:
https://programmingdesignsystems.com/color/perceptually-uniform-color-spaces/index.html
https://www.hsluv.org/

**Comment by tebjan** [comment]
Yes, so "linear" is the physically correct reference color space where all color math should happen. "sRGB" is the most common color space to store colors in low-bit formats and "gamma" is the color space to display colors on a display.

when we want to have more than these, we have to do some kind of infrastructure where one can plug in any transfer function. so similar to the keying shader we can have a base shader and then implement all the transfer functions separately and add more later.

So I think for now we have:
SRgbToLinear
LinearToSRgb
LinearToGamma

**Comment by bj-rn** [comment]
No GammaToLinear? And will you PR the "missing" methods to the Stride ColorUtility?

**Comment by mhusinsky** [comment]
for sRGB/rec709/... it might make sense to have an infrastructure as well, as these models all have a linear part for lower regions and a gamma-curved part for most of the rest. afaik only the values for these parts differ.

**Comment by tebjan** [comment]
> No GammaToLinear? And will you PR the "missing" methods to the Stride ColorUtility?

this is probably the least used one, but sure, if you find a good algorithm.
for now, just add a ColorUtilityTemp and add everything there, we can make a PR once t is all settled.

> Is this also what the RGBTosRGB color node does?

the CPU node in the CoreLib does the precise conversion in both directions:
for reference, this is the r channel:
```c
if (srgb.R <= 0.04045f)
{
    r = srgb.R / 12.92f;
}
else
{
    r = (float)Math.Pow((srgb.R + 0.055f) / (1.0f + 0.055f), 2.4f);
}
```

> which methods would LinearToGamma and GammaToLinear use? I thought the stuff you posted would convert from sRGB to gamma and vice versa, not from/to linear.

Linear to gamma is `pow(c, gamma)` and the inverse is `pow(c, 1/gamma)`. which is very expensive in shaders. but hopefully not used often. they (should) convert from/to linear.

> for sRGB/rec709/... it might make sense to have an infrastructure as well, as these models all have a linear part for lower regions and a gamma-curved part for most of the rest. afaik only the values for these parts differ.

that might be a bit over-engineered, I think every function can implement the full transfer, the algorithms aren't that long. but if you fancy doing it, enjoy!

**Comment by tebjan** [comment]
so again the list:
SRgbToLinear (fast/precise)
LinearToSRgb (fast/precise)
LinearToGamma
GammaToLinear

**Comment by bj-rn** [comment]
I think someone else needs to take over dealing with the color stuff. I just can't wrap my head around it.
image

**Comment by tebjan** [comment]
sure, just add me as a collaborator to your repo, so I can push to the branch.

**Comment by tebjan** [comment]
> Someone else needs to deal with the color stuff. I just can't wrap my head around it.

the issue here was that when changing the color space, the texture format also has to change to tell the sampler how to sample the texture.

**Comment by bj-rn** [comment]
Just came across this blog:
https://bottosson.github.io/

**Comment by tebjan** [comment]
All conversions are now implemented. Thanks for the work @bj-rn .

**Comment by tebjan** [comment]
@mhusinsky here are some more: http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html

**Pull request closed without merging**
