### PR TITLE
TextureFX IV (A New Hope)

### PR DESCRIPTION
**Pull request by bj-rn**
please refer to https://github.com/vvvv/VL.Stride/pull/387, https://github.com/vvvv/VL.Stride/pull/390 and https://github.com/vvvv/VL.Stride/pull/392 for previous comments

### CODE REVIEW

**Comment by tebjan** [comment]
so in order to tackle this, we thought that it would be best to separate the individual nodes by their intended use and how "basic" or "core" they are.  so can we get a list of all new nodes and sort them into 3 groups:
* core, nodes that absolutely should be in the core lib, like ChangeFormat, Swizzle
* practical, nodes that are useful and people would use in their projects regularly, like MapColor, BackgroundSubtraction
* gimmick, nodes that are rather esoteric, like Mandelbrot, Anaglyph

we can then focus on the core and practical nodes to make them as good as possible with the correct code style, performance, and using stride features, the rest of the gimmicks can then just be set to experimental and put there so it's there to use but without any guarantee that it will stay like this. we could even think about an extra community package that contains all the lesser-used gimmicks where everyone can throw in their effects and the quality control is less strict. we would also move things like Tunnels to this experimental package.

so in order to do that, we should probably make a google doc or a mind map sort the nodes in an easier way, and add tasks to them. after sorting them, it would probably be the best workflow to make one PR per node group.

@bj-rn  do you have a copy&pasteable string list of all nodes contained in the PR?

**Comment by bj-rn** [comment]
Anaglyph

BackgroundSubstraction
BlurGlow
BlurPerfector
BubbleNoise
Bump

ChangeFormat
ChannelKey
Colorize
ColorMap (->MapColor)
ColorConvert (->ConvertColor)
CrossStitch

DeInterlace
Directional Blur
Dissolve
Dither
Dots
DropShadow

Edge

Halo
Hatch (Cross)
Hatch (Dot)
Hatch (FromTexture)
Hatch (Line)

Kaleidoscope

LinearDepth
Liquish
Lomograph

Magnify
Mandelbrot
Median
Metallica
Muffy

NormalGlow
Palette
PolarCoordinates

Ripple

Sharpen
Swizzle

ToLinear
Transform
Tricolor

**Comment by bj-rn** [comment]
Please don't use google docs. 
https://cryptpad.fr/sheet/#/2/sheet/edit/wu-HEppevxpFch7s6SLRgzv+/

**Comment by tebjan** [comment]
> Please don't use google docs.
> https://cryptpad.fr/sheet/#/2/sheet/edit/wu-HEppevxpFch7s6SLRgzv+/

thanks, great to see them all at once. unfortunately, this doesn't have undo, but it should do the job for now. can it sort the rows by category now?

or, if you want, just start the first PR with the core ones.

**Comment by bj-rn** [comment]
Mh. So now I should do pull requests for single nodes? How would I go on about it,  create a new branch for each of them and cherry pick the respective commits? 
The effects marked as _core_ now are all in separate files. Others changed the same files though (TextureFXTechniqueEnums.cs, VL.Stride.Rendering.TextureFX.vl), won't those contain the changes committed before them? 
Might be easier to start from scratch with new branches readding the changes manually.

**Comment by tebjan** [comment]
> So now I should do pull requests for single nodes? How would I go on about it, create a new branch for each of them and cherry pick the respective commits?

not the individual nodes, just for each group. we'll polish the core and practical ones as good as possible and then put all the remaining gimmicks into the experimental category.

I think the easiest way is to make a new branch from the current develop branch, and copy the files from the branch in this PR to the newly created branch.

core should be easy, because it is just 3 nodes, right?

**Comment by bj-rn** [comment]
@tebjan 
https://github.com/vvvv/VL.Stride/pull/395

**Comment by joreg** [comment]
@bj-rn a heads-up on this: we're currently improving the texturefx system internally. so we've planned to accept this PR as is when we're ready, and make the relevant changes to all the fx. we'll then have them all included, some maybe still marked as "experimental" for further discussion.

**Comment by joreg** [comment]
This is now merged and available in latest previews. Massive thanks for your work on this!

**Pull request merged**
