### PR TITLE
Mesh and model viewers

### PR DESCRIPTION
**Pull request by gregsn**
added
MaterialViewer
MeshViewer
ModelViewer

### CODE REVIEW

**Review by tebjan — COMMENTED** [review]
Great stuff!

A few ideas for improvement:
The model viewer only renders the wireframe for the first mesh and the transformation seems to be a tiny bit off, I think the mesh part that draws the wireframe doesn't get the mesh transformation if the model has skinning.

image

It also looks like the bounding box of the model should be used, instead of the mesh one, which could only be a part of the whole model.

The material viewer doesn't seem to render displacement for meshes.

The bright gray background color looks a bit too plain for my taste, I'd set that to the tooltip background color:
image

Maybe separate model/material viewer from mesh viewer, since the wireframe is hard to get right for model/material untile we have individual pipeline processors. see #360

**Comment by tebjan** [comment]
Added a few tweaks, feel free to revert.
* background color
* bounding box for camera fix
* disabled wireframe for model and material

Not sure whether the object or the camera should rotate... @antongit what do you think?
If the object rotates, the change of shadows is a bit more dynamic, if the camera rotates around the object, everything is static.

**Comment by antongit** [comment]
Wow!

- Unfortunately I can't say what is better - to rotate the model or the camera as I don't have enough experience here.
- On my machine it takes very long time for the Materials to show up in the tooltip. Maybe it can't be improved, because of the compilation. It's just a bit of spassverderber. You hover over the Material and wait-and-wait-and-wait-and-wait, ah! now.

**Comment by tebjan** [comment]
Did some final tweaks and also added a short fade in to avoid the white flashes when the tooltip opens.

**Pull request merged**
