### PR TITLE
TextureFX II

### PR DESCRIPTION
**Pull request by bj-rn**
See https://github.com/vvvv/VL.Stride/pull/387 for initial comments.

### CODE REVIEW

**Comment by azeno** [comment]
Ok, thanks for opening again.

So as I was saying in the previous PR, we need to take care that those internal implementations get disposed (like in `ColorMap`). If they're all patched with a `Cache` region holding the state, then simply enabling `Dispose Cached Outputs` should be enough.

We also need an idea about the name clash of `ColorMap`.

**Comment by bj-rn** [comment]
A more general question: Is using interfaces (for techniques) the way to go? Or is a _Switch_ statement  as used [here](https://github.com/bj-rn/VL.Stride/blob/dev/bj-rn/texturefx/packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_Internal_TextureFX.sdsl) for example also a possibilty. Like I said in the original pull request: it is a lot less work and at least in my opinion far nicer readability wise. I don't know if there are any major performance impacts though.

**Comment by tebjan** [comment]
The correct way to do it would be shader composition. Depending on what you choose, the correct shader gets compiled. 

That means that the part of the shader that differs will be set by an enum.

Runtime switch and if statements are rather bad for performance and would solve the problem on the wrong end. 

So for now we can only patch what a technique enum would do, if we had it. 

Stride also had a quite advanced system for that, which we haven't touched at all yet. Their effect files could be compared to scriptable dx techniques...

**Comment by bj-rn** [comment]
Ok for now I will enable `Dispose Cached Outputs`, "re-write" and wrap those shaders that are currently using a switch statement:?
* Halo
* Lomograph (already using a switch in the original implementation)
* Palette

**Comment by tebjan** [comment]
> Runtime switch and if statements are rather bad for performance and would solve the problem on the wrong end.
> 
> So for now we can only patch what a technique enum would do, if we had it.

it seems that modern GPUs can optimize branches that depend only on a uniform value (doesn't change per vertex/pixel), found an answer here: https://stackoverflow.com/a/37837060/355485

**Pull request merged**
